// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { TerminologyEntry, CodedTerminologyEntry } from "../terminology-types";

export type USCoreCarePlanCategoryExtensionCodesCode = "assess-plan";
export const USCoreCarePlanCategoryExtensionCodesCodeSystem = {
    canonicalUrl: "http://hl7.org/fhir/us/core/CodeSystem/careplan-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "CodeSystem",
    contentMode: "complete",
    codes: ["assess-plan"],
    displays: {
        "assess-plan": "Assessment and Plan of Treatment",
    },
} as const satisfies CodedTerminologyEntry<USCoreCarePlanCategoryExtensionCodesCode>;

export type USCoreCategoryCode = "sdoh" | "functional-status" | "disability-status" | "cognitive-status" | "treatment-intervention-preference" | "care-experience-preference" | "observation-adi-documentation";
export const USCoreCategoryCodeSystem = {
    canonicalUrl: "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "CodeSystem",
    contentMode: "complete",
    codes: ["sdoh", "functional-status", "disability-status", "cognitive-status", "treatment-intervention-preference", "care-experience-preference", "observation-adi-documentation"],
    displays: {
        sdoh: "SDOH",
        "functional-status": "Functional Status",
        "disability-status": "Disability Status",
        "cognitive-status": "Cognitive Status",
        "treatment-intervention-preference": "Treatment Intervention Preference",
        "care-experience-preference": "Care Experience Preference",
        "observation-adi-documentation": "Observation ADI Documentation",
    },
} as const satisfies CodedTerminologyEntry<USCoreCategoryCode>;

export type USCoreConditionCategoryExtensionCodesCode = "problem" | "health-concern";
export const USCoreConditionCategoryExtensionCodesCodeSystem = {
    canonicalUrl: "http://hl7.org/fhir/us/core/CodeSystem/condition-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "CodeSystem",
    contentMode: "complete",
    codes: ["problem", "health-concern"],
    displays: {
        problem: "Problem",
        "health-concern": "Health Concern",
    },
} as const satisfies CodedTerminologyEntry<USCoreConditionCategoryExtensionCodesCode>;

export type USCoreDocumentReferencesCategoryCodesCode = "clinical-note";
export const USCoreDocumentReferencesCategoryCodesCodeSystem = {
    canonicalUrl: "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "CodeSystem",
    contentMode: "complete",
    codes: ["clinical-note"],
    displays: {
        "clinical-note": "Clinical Note",
    },
} as const satisfies CodedTerminologyEntry<USCoreDocumentReferencesCategoryCodesCode>;

export type USCoreProvenancePaticipantTypeExtensionCodesCode = "transmitter";
export const USCoreProvenancePaticipantTypeExtensionCodesCodeSystem = {
    canonicalUrl: "http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "CodeSystem",
    contentMode: "complete",
    codes: ["transmitter"],
    displays: {
        transmitter: "Transmitter",
    },
} as const satisfies CodedTerminologyEntry<USCoreProvenancePaticipantTypeExtensionCodesCode>;

export const NarrativeStatusValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-narrative-status",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreClinicalNoteTypeValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-clinical-note-type",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreClinicalResultObservationCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-clinical-result-observation-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreConditionCodesCurrentValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code-current",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreConditionCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreDiagnosticReportCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreDocumentReferenceCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreDocumentReferenceTypeValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreGoalCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-goal-description",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreLaboratoryTestCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-laboratory-test-codes",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreNonLaboratoryCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreObservationSmokingStatusStatusValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-observation-smoking-status-status",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreProblemOrHealthConcernValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreProcedureCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreProvenancePaticipantTypeCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-provenance-participant-type",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreScreeningAssessmentConditionCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-screening-assessment-condition-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreScreeningAssessmentObservationCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-screening-assessment-observation-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreScreeningAssessmentObservationMaximumCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-screening-assessment-observation-maximum-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreServiceRequestCategoryCodesValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-servicerequest-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreSimpleObservationCategoryValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-simple-observation-category",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;

export const USCoreSpecimenConditionValueSet = {
    canonicalUrl: "http://hl7.org/fhir/us/core/ValueSet/us-core-specimen-condition",
    packageId: "hl7.fhir.us.core",
    packageVersion: "8.0.1",
    verification: "registry-integrity",
    resourceType: "ValueSet",
} as const satisfies TerminologyEntry;
