// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Provenance, ProvenanceAgent } from "../../hl7-fhir-r4-core/Provenance.js";
import type { Reference } from "../../hl7-fhir-r4-core/Reference.js";

export type USCoreProvenance_Agent_ProvenanceAuthorSliceFlat = Omit<ProvenanceAgent, "type">;
export type USCoreProvenance_Agent_ProvenanceAuthorSliceFlatAll = USCoreProvenance_Agent_ProvenanceAuthorSliceFlat;

export type USCoreProvenance_Agent_ProvenanceTransmitterSliceFlat = Omit<ProvenanceAgent, "type">;
export type USCoreProvenance_Agent_ProvenanceTransmitterSliceFlatAll = USCoreProvenance_Agent_ProvenanceTransmitterSliceFlat;

import {
    ensureProfile,
    applySliceMatch,
    matchesValue,
    setArraySlice,
    getArraySlice,
    ensureSliceDefaults,
    setArraySliceAll,
    getArraySliceAll,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateSliceFields,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateChoiceProhibited,
    validateMustSupport,
} from "../../profile-helpers.js";

export type USCoreProvenanceProfileRaw = {
    target: Reference<string /* Resource */>[];
    recorded: string;
    agent: ProvenanceAgent[];
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreProvenanceProfile {
    static readonly resourceType = "Provenance";
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance";

    private static readonly ProvenanceAuthorSliceMatch: Record<string, unknown> = {
        "type": {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/provenance-participant-type","code":"author"}]},
    }
    private static readonly ProvenanceTransmitterSliceMatch: Record<string, unknown> = {
        "type": {"coding":[{"system":"http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type","code":"transmitter"}]},
    }

    private resource: Provenance;

    constructor (resource: Provenance) {
        this.resource = resource;
    }

    static from (resource: Provenance) : USCoreProvenanceProfile {
        if (!resource.meta?.profile?.includes(USCoreProvenanceProfile.canonicalUrl)) {
            throw new Error(`USCoreProvenanceProfile: meta.profile must include ${USCoreProvenanceProfile.canonicalUrl}`)
        }
        const profile = new USCoreProvenanceProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static is (resource: unknown) : resource is Provenance {
        if (typeof resource !== "object" || resource === null) return false;
        const r = resource as { resourceType?: string; meta?: { profile?: string[] } };
        if (r.resourceType !== "Provenance") return false;
        return (r.meta?.profile ?? []).includes(USCoreProvenanceProfile.canonicalUrl);
    }

    static apply (resource: Provenance) : USCoreProvenanceProfile {
        ensureProfile(resource, USCoreProvenanceProfile.canonicalUrl);
        return new USCoreProvenanceProfile(resource);
    }

    static createResource (args: USCoreProvenanceProfileRaw) : Provenance {
        const resource: Provenance = {
            resourceType: "Provenance",
            target: args.target,
            recorded: args.recorded,
            agent: args.agent,
            meta: { profile: [USCoreProvenanceProfile.canonicalUrl] },
        }
        return resource;
    }

    static create (args: USCoreProvenanceProfileRaw) : USCoreProvenanceProfile {
        const resource = USCoreProvenanceProfile.createResource(args);
        return USCoreProvenanceProfile.apply(resource);
    }

    toResource () : Provenance {
        return this.resource;
    }

    // Field accessors
    getTarget () : Reference<string /* Resource */>[] | undefined {
        return this.resource.target as Reference<string /* Resource */>[] | undefined;
    }

    setTarget (value: Reference<string /* Resource */>[]) : this {
        Object.assign(this.resource, { target: value });
        return this;
    }

    getRecorded () : string | undefined {
        return this.resource.recorded as string | undefined;
    }

    setRecorded (value: string) : this {
        Object.assign(this.resource, { recorded: value });
        return this;
    }

    getAgent () : ProvenanceAgent[] | undefined {
        return this.resource.agent as ProvenanceAgent[] | undefined;
    }

    setAgent (value: ProvenanceAgent[]) : this {
        Object.assign(this.resource, { agent: value });
        return this;
    }

    // Extensions
    // Slices
    public setProvenanceAuthor (input: (USCoreProvenance_Agent_ProvenanceAuthorSliceFlat | ProvenanceAgent)[]): this {
        const match = USCoreProvenanceProfile.ProvenanceAuthorSliceMatch
        const arr = this.resource.agent ??= []
        const values = input.map(item => matchesValue(item, match) ? item as ProvenanceAgent : applySliceMatch<ProvenanceAgent>(item, match))
        setArraySliceAll(arr, match, values)
        return this
    }

    public setProvenanceTransmitter (input: (USCoreProvenance_Agent_ProvenanceTransmitterSliceFlat | ProvenanceAgent)[]): this {
        const match = USCoreProvenanceProfile.ProvenanceTransmitterSliceMatch
        const arr = this.resource.agent ??= []
        const values = input.map(item => matchesValue(item, match) ? item as ProvenanceAgent : applySliceMatch<ProvenanceAgent>(item, match))
        setArraySliceAll(arr, match, values)
        return this
    }

    public getProvenanceAuthor(mode: 'flat'): USCoreProvenance_Agent_ProvenanceAuthorSliceFlatAll[] | undefined;
    public getProvenanceAuthor(mode: 'raw'): ProvenanceAgent[] | undefined;
    public getProvenanceAuthor(): USCoreProvenance_Agent_ProvenanceAuthorSliceFlatAll[] | undefined;
    public getProvenanceAuthor (mode: 'flat' | 'raw' = 'flat'): (USCoreProvenance_Agent_ProvenanceAuthorSliceFlatAll | ProvenanceAgent)[] | undefined {
        const match = USCoreProvenanceProfile.ProvenanceAuthorSliceMatch
        const items = getArraySliceAll(this.resource.agent, match)
        if (items.length === 0) return undefined
        if (mode === 'raw') return items
        return items as unknown as USCoreProvenance_Agent_ProvenanceAuthorSliceFlatAll[]
    }

    public getProvenanceTransmitter(mode: 'flat'): USCoreProvenance_Agent_ProvenanceTransmitterSliceFlatAll[] | undefined;
    public getProvenanceTransmitter(mode: 'raw'): ProvenanceAgent[] | undefined;
    public getProvenanceTransmitter(): USCoreProvenance_Agent_ProvenanceTransmitterSliceFlatAll[] | undefined;
    public getProvenanceTransmitter (mode: 'flat' | 'raw' = 'flat'): (USCoreProvenance_Agent_ProvenanceTransmitterSliceFlatAll | ProvenanceAgent)[] | undefined {
        const match = USCoreProvenanceProfile.ProvenanceTransmitterSliceMatch
        const items = getArraySliceAll(this.resource.agent, match)
        if (items.length === 0) return undefined
        if (mode === 'raw') return items
        return items as unknown as USCoreProvenance_Agent_ProvenanceTransmitterSliceFlatAll[]
    }

    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "USCoreProvenance"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "target"),
                ...validateReference(res, profileName, "target", ["Bundle","CodeSystem","Observation","OperationOutcome","Patient","Provenance"]),
                ...validateRequired(res, profileName, "recorded"),
                ...validateRequired(res, profileName, "agent"),
            ],
            warnings: [],
        }
    }

}

