# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from fhir_types.hl7_fhir_r4_core.patient import Patient
from fhir_types.hl7_fhir_r4_core.base import HumanName, Identifier
from .profile_helpers import (
    build_resource,
    ensure_profile,
    is_extension,
    get_extension_value,
    push_extension,
    extract_complex_extension,
    validate_must_support,
    validate_required,
)


class UscorePatientProfile:
    """The US Core Patient Profile inherits from the FHIR [Patient](https://hl7.org/fhir/R4/patient.html) resource; refer to it for scope and usage definitions. This profile meets the requirements of the [U.S. Core Data for Interoperability (USCDI)](https://www.healthit.gov/isp/united-states-core-data-interoperability-uscdi) *Patient Demographics/Information* Data Class. It sets minimum expectations for the Patient resource to record, search, and fetch basic demographics and other administrative information about an individual patient. It specifies which core elements, extensions, vocabularies, and value sets **SHALL** be present and constrains how the elements are used. Providing the floor for standards development for specific use cases promotes interoperability and adoption.

    CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient
    """

    canonical_url: str = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"

    def __init__(self, resource: Patient) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Patient) -> "UscorePatientProfile":
        meta = getattr(resource, "meta", None)
        profiles = getattr(meta, "profile", None) if meta is not None else None
        if profiles is None or cls.canonical_url not in profiles:
            raise ValueError(f"UscorePatientProfile: meta.profile must include {cls.canonical_url}")
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Patient) -> "UscorePatientProfile":
        ensure_profile(resource, cls.canonical_url)
        return cls(resource)

    @classmethod
    def create_resource(cls, *, identifier: list[Identifier], name: list[HumanName]) -> Patient:
        return build_resource(
            Patient,
            resource_type="Patient",
            identifier=identifier,
            name=name,
            meta={"profile": [cls.canonical_url]},
        )

    @classmethod
    def create(cls, *, identifier: list[Identifier], name: list[HumanName]) -> "UscorePatientProfile":
        return cls.apply(cls.create_resource(identifier=identifier, name=name))

    def to_resource(self) -> Patient:
        return self._resource

    def get_identifier(self) -> list[Identifier] | None:
        return getattr(self._resource, "identifier", None)

    def set_identifier(self, value: list[Identifier]) -> "UscorePatientProfile":
        setattr(self._resource, "identifier", value)
        return self

    def get_name(self) -> list[HumanName] | None:
        return getattr(self._resource, "name", None)

    def set_name(self, value: list[HumanName]) -> "UscorePatientProfile":
        setattr(self._resource, "name", value)
        return self

    def get_race(self) -> dict | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race")), None)
        if ext is None:
            return None
        config = [{"name": "ombCategory", "valueField": "value_coding", "isArray": False}, {"name": "detailed", "valueField": "value_coding", "isArray": True}, {"name": "text", "valueField": "value_string", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_race(self, value: dict) -> "UscorePatientProfile":
        sub_extensions = []
        if value.get("ombCategory") is not None:
            sub_extensions.append({"url": "ombCategory", "value_coding": value["ombCategory"]})
        for item in value.get("detailed", []):
            sub_extensions.append({"url": "detailed", "value_coding": item})
        if value.get("text") is not None:
            sub_extensions.append({"url": "text", "value_string": value["text"]})
        push_extension(self._resource, {"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race", "extension": sub_extensions})
        return self

    def get_ethnicity(self) -> dict | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity")), None)
        if ext is None:
            return None
        config = [{"name": "ombCategory", "valueField": "value_coding", "isArray": False}, {"name": "detailed", "valueField": "value_coding", "isArray": True}, {"name": "text", "valueField": "value_string", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_ethnicity(self, value: dict) -> "UscorePatientProfile":
        sub_extensions = []
        if value.get("ombCategory") is not None:
            sub_extensions.append({"url": "ombCategory", "value_coding": value["ombCategory"]})
        for item in value.get("detailed", []):
            sub_extensions.append({"url": "detailed", "value_coding": item})
        if value.get("text") is not None:
            sub_extensions.append({"url": "text", "value_string": value["text"]})
        push_extension(self._resource, {"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity", "extension": sub_extensions})
        return self

    def get_tribal_affiliation(self) -> dict | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation")), None)
        if ext is None:
            return None
        config = [{"name": "tribalAffiliation", "valueField": "value_codeable_concept", "isArray": False}, {"name": "isEnrolled", "valueField": "value_boolean", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_tribal_affiliation(self, value: dict) -> "UscorePatientProfile":
        sub_extensions = []
        if value.get("tribalAffiliation") is not None:
            sub_extensions.append({"url": "tribalAffiliation", "value_codeable_concept": value["tribalAffiliation"]})
        if value.get("isEnrolled") is not None:
            sub_extensions.append({"url": "isEnrolled", "value_boolean": value["isEnrolled"]})
        push_extension(self._resource, {"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation", "extension": sub_extensions})
        return self

    def get_sex(self) -> Coding | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex")), None)
        if ext is None:
            return None
        return get_extension_value(ext, "value_coding")

    def set_sex(self, value) -> "UscorePatientProfile":
        push_extension(self._resource, {"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex", "value_coding": value})
        return self

    def get_interpreter_required(self) -> Coding | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed")), None)
        if ext is None:
            return None
        return get_extension_value(ext, "value_coding")

    def set_interpreter_required(self, value) -> "UscorePatientProfile":
        push_extension(self._resource, {"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed", "value_coding": value})
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "UscorePatientProfile"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "identifier"))
        errors.extend(validate_required(self._resource, profile_name, "name"))
        warnings.extend(validate_must_support(self._resource, profile_name, "birth_date"))
        warnings.extend(validate_must_support(self._resource, profile_name, "address"))
        return {"errors": errors, "warnings": warnings}

