# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhir_types.hl7_fhir_r4_core.base import Meta
from fhir_types.hl7_fhir_r4_core.base import Element


class Resource(BaseModel):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    resource_type: str = Field(
        default='Resource',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Resource'
    )
    id: str | None = Field(None, alias="id", serialization_alias="id")
    id_extension: Element | None = Field(None, alias="_id", serialization_alias="_id")
    implicit_rules: str | None = Field(None, alias="implicitRules", serialization_alias="implicitRules")
    implicit_rules_extension: Element | None = Field(None, alias="_implicitRules", serialization_alias="_implicitRules")
    language: str | None = Field(None, alias="language", serialization_alias="language")
    language_extension: Element | None = Field(None, alias="_language", serialization_alias="_language")
    meta: Meta | None = Field(None, alias="meta", serialization_alias="meta")

    def to_json(self, indent: int | None = None, by_alias: bool = False, exclude_unset: bool = True) -> str:
        return self.model_dump_json(by_alias=by_alias, exclude_unset=exclude_unset, exclude_none=True, indent=indent)

    @classmethod
    def from_json(cls, json: str) -> Resource:
        return cls.model_validate_json(json)

