// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    applyFixedValue,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateSliceFields,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateChoiceProhibited,
    validateMustSupport,
} from "../../profile-helpers";

export type birthTimeProfileRaw = {
    valueDateTime: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthTime (pkg: hl7.fhir.r4.core#4.0.1)
export class birthTimeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthTime";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : birthTimeProfile {
        const profile = new birthTimeProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static is (resource: unknown) : resource is Extension {
        if (typeof resource !== "object" || resource === null) return false;
        return (resource as { url?: string }).url === birthTimeProfile.canonicalUrl;
    }

    static apply (resource: Extension) : birthTimeProfile {
        resource.url = birthTimeProfile.canonicalUrl;
        applyFixedValue(resource, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthTime");
        return new birthTimeProfile(resource);
    }

    static createResource (args: birthTimeProfileRaw) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
            valueDateTime: args.valueDateTime,
        }
        return resource;
    }

    static create (args: birthTimeProfileRaw) : birthTimeProfile {
        const resource = birthTimeProfile.createResource(args);
        return birthTimeProfile.apply(resource);
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined;
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "birthTime"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", birthTimeProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueDateTime"]),
                ...validateChoiceProhibited(res, profileName, ["valueBase64Binary","valueBoolean","valueCanonical","valueCode","valueDate","valueDecimal","valueId","valueInstant","valueInteger","valueMarkdown","valueOid","valuePositiveInt","valueString","valueTime","valueUnsignedInt","valueUri","valueUrl","valueUuid","valueAddress","valueAge","valueAnnotation","valueAttachment","valueCodeableConcept","valueCoding","valueContactPoint","valueCount","valueDistance","valueDuration","valueHumanName","valueIdentifier","valueMoney","valuePeriod","valueQuantity","valueRange","valueRatio","valueReference","valueSampledData","valueSignature","valueTiming","valueContactDetail","valueContributor","valueDataRequirement","valueExpression","valueParameterDefinition","valueRelatedArtifact","valueTriggerDefinition","valueUsageContext","valueDosage","valueMeta"]),
            ],
            warnings: [],
        }
    }

}

