// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    applyFixedValue,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateSliceFields,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type own_prefixProfileRaw = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/humanname-own-prefix (pkg: hl7.fhir.r4.core#4.0.1)
export class own_prefixProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : own_prefixProfile {
        const profile = new own_prefixProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static is (resource: unknown) : resource is Extension {
        if (typeof resource !== "object" || resource === null) return false;
        return (resource as { url?: string }).url === own_prefixProfile.canonicalUrl;
    }

    static apply (resource: Extension) : own_prefixProfile {
        resource.url = own_prefixProfile.canonicalUrl;
        applyFixedValue(resource, "url", "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix");
        return new own_prefixProfile(resource);
    }

    static createResource (args: own_prefixProfileRaw) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix",
            valueString: args.valueString,
        }
        return resource;
    }

    static create (args: own_prefixProfileRaw) : own_prefixProfile {
        const resource = own_prefixProfile.createResource(args);
        return own_prefixProfile.apply(resource);
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined;
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "own-prefix"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", own_prefixProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueString"]),
            ],
            warnings: [],
        }
    }

}

