// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../../hl7-fhir-r4-core/Address";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    applyFixedValue,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateSliceFields,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type birthPlaceProfileRaw = {
    valueAddress: Address;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthPlace (pkg: hl7.fhir.r4.core#4.0.1)
export class birthPlaceProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : birthPlaceProfile {
        const profile = new birthPlaceProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static is (resource: unknown) : resource is Extension {
        if (typeof resource !== "object" || resource === null) return false;
        return (resource as { url?: string }).url === birthPlaceProfile.canonicalUrl;
    }

    static apply (resource: Extension) : birthPlaceProfile {
        resource.url = birthPlaceProfile.canonicalUrl;
        applyFixedValue(resource, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthPlace");
        return new birthPlaceProfile(resource);
    }

    static createResource (args: birthPlaceProfileRaw) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            valueAddress: args.valueAddress,
        }
        return resource;
    }

    static create (args: birthPlaceProfileRaw) : birthPlaceProfile {
        const resource = birthPlaceProfile.createResource(args);
        return birthPlaceProfile.apply(resource);
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueAddress () : Address | undefined {
        return this.resource.valueAddress as Address | undefined;
    }

    setValueAddress (value: Address) : this {
        Object.assign(this.resource, { valueAddress: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "birthPlace"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", birthPlaceProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueAddress"]),
            ],
            warnings: [],
        }
    }

}

