import { describe, expect, it } from "bun:test";
import { APIBuilder } from "@root/api/builder";
import { registerFromManager } from "@root/typeschema/register";
import { mkErrorLogger } from "@typeschema-test/utils";

const packageMeta = { name: "fixture.ig", version: "1.2.3" };

const resources = [
    {
        resourceType: "CodeSystem",
        id: "complete-example",
        name: "CompleteExample",
        url: "http://example.test/CodeSystem/complete",
        content: "complete",
        concept: [
            { code: "second", display: "Second display" },
            { code: "first", display: "First display" },
        ],
    },
    {
        resourceType: "CodeSystem",
        id: "not-present-example",
        name: "NotPresentExample",
        url: "http://example.test/CodeSystem/not-present",
        content: "not-present",
        concept: [{ code: "must-not-appear", display: "Must not appear" }],
    },
    {
        resourceType: "CodeSystem",
        id: "example-content",
        name: "ExampleContent",
        url: "http://example.test/CodeSystem/example",
        content: "example",
        concept: [{ code: "also-forbidden", display: "Also forbidden" }],
    },
    {
        resourceType: "ValueSet",
        id: "expanded-value-set",
        name: "ExpandedValueSet",
        url: "http://example.test/ValueSet/expanded",
        expansion: {
            timestamp: "2026-08-19T00:00:00Z",
            contains: [{ code: "expansion-only", display: "Expansion only" }],
        },
    },
    {
        resourceType: "NamingSystem",
        id: "local-identifiers",
        name: "LocalIdentifiers",
        uniqueId: [{ type: "uri", value: "http://example.test/NamingSystem/local-identifiers", preferred: true }],
    },
] as const;

const generateTerminology = async (
    verification = "registry-integrity",
    sourceResources: readonly object[] = resources,
) => {
    const manager = {
        packageJson: async () => ({ ...packageMeta, dependencies: {} }),
        search: async () => sourceResources,
    } as unknown as Parameters<typeof registerFromManager>[0];
    const register = await registerFromManager(manager, { focusedPackages: [packageMeta] });

    const result = await new APIBuilder({ register, logger: mkErrorLogger() })
        .typescript({
            inMemoryOnly: true,
            terminology: {
                packageVerification: { "fixture.ig@1.2.3": verification },
            },
        })
        .generate();

    if (!result.success) throw new Error(`generation failed: ${result.errors.join(", ")}`);
    const output = result.filesGenerated.typescript!["generated/types/fixture-ig/terminology.ts"];
    if (output === undefined) throw new Error("terminology module was not generated");
    return output;
};

describe("TypeScript terminology surface", () => {
    it("emits package provenance and declared content for every terminology resource", async () => {
        expect(await generateTerminology()).toMatchInlineSnapshot(`
          "// WARNING: This file is autogenerated by @atomic-ehr/codegen.
          // GitHub: https://github.com/atomic-ehr/codegen
          // Any manual changes made to this file may be overwritten.

          export const CompleteExampleCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/complete",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "complete",
              codes: ["second", "first"],
              displays: {
                  "second": "Second display",
                  "first": "First display",
              },
          } as const;
          export type CompleteExampleCode = (typeof CompleteExampleCodeSystem.codes)[number];

          export const ExampleContentCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/example",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "example",
          } as const;

          export const NotPresentExampleCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/not-present",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "not-present",
          } as const;

          export const LocalIdentifiersNamingSystem = {
              canonicalUrl: "http://example.test/NamingSystem/local-identifiers",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "NamingSystem",
              contentMode: null,
          } as const;

          export const ExpandedValueSetValueSet = {
              canonicalUrl: "http://example.test/ValueSet/expanded",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "ValueSet",
              contentMode: null,
          } as const;
          "
        `);
    });

    it("does not derive constants from non-complete CodeSystems or ValueSet expansions", async () => {
        const output = await generateTerminology();

        expect(output).not.toContain("must-not-appear");
        expect(output).not.toContain("also-forbidden");
        expect(output).not.toContain("expansion-only");
        expect(output).not.toContain("export type NotPresentExampleCode =");
        expect(output).not.toContain("export type ExampleContentCode =");
    });

    it("preserves complete CodeSystem concept order and exact displays", async () => {
        const output = await generateTerminology();
        const sourceConcepts = resources[0].concept;

        expect(output.indexOf(JSON.stringify(sourceConcepts[0].code))).toBeLessThan(
            output.indexOf(JSON.stringify(sourceConcepts[1].code)),
        );
        for (const concept of sourceConcepts) {
            expect(output).toContain(`${JSON.stringify(concept.code)}: ${JSON.stringify(concept.display)}`);
        }
    });

    it("emits no concept content for an unverifiable package", async () => {
        const output = await generateTerminology("unverifiable");

        expect(output).toContain('canonicalUrl: "http://example.test/CodeSystem/complete"');
        expect(output).toContain('packageVersion: "1.2.3"');
        expect(output).toContain('verification: "unverifiable"');
        expect(output).not.toContain("codes:");
        expect(output).not.toContain("displays:");
        expect(output).not.toContain("export type CompleteExampleCode");
    });

    it("disambiguates resources that declare the same FHIR name", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "ValueSet",
                id: "radiation-relevant-billing-code",
                name: "RadiationRelevantBillingCodeVS",
                url: "http://example.test/ValueSet/radiation-relevant-billing-code",
            },
            {
                resourceType: "ValueSet",
                id: "radiation-relevant-billing-codes",
                name: "RadiationRelevantBillingCodeVS",
                url: "http://example.test/ValueSet/radiation-relevant-billing-codes",
            },
        ]);

        const symbols = [...output.matchAll(/^export const (\w+)/gm)].map((match) => match[1]);
        expect(symbols).toHaveLength(2);
        expect(new Set(symbols).size).toBe(2);
        expect(() => new Bun.Transpiler({ loader: "ts" }).transformSync(output)).not.toThrow();
    });
});
