import { describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import type { FHIRSchema } from "@atomic-ehr/fhirschema";
import { APIBuilder } from "@root/api/builder";
import { registerFromManager } from "@root/typeschema/register";
import { enrichFHIRSchema } from "@root/typeschema/types";
import { mkErrorLogger } from "@typeschema-test/utils";

const packageMeta = { name: "fixture.ig", version: "1.2.3" };

const resources = [
    {
        resourceType: "CodeSystem",
        id: "complete-example",
        name: "CompleteExample",
        url: "http://example.test/CodeSystem/complete",
        content: "complete",
        concept: [
            { code: "second", display: "Second display" },
            { code: "first", display: "First display" },
        ],
    },
    {
        resourceType: "CodeSystem",
        id: "not-present-example",
        name: "NotPresentExample",
        url: "http://example.test/CodeSystem/not-present",
        content: "not-present",
        concept: [{ code: "must-not-appear", display: "Must not appear" }],
    },
    {
        resourceType: "CodeSystem",
        id: "example-content",
        name: "ExampleContent",
        url: "http://example.test/CodeSystem/example",
        content: "example",
        concept: [{ code: "also-forbidden", display: "Also forbidden" }],
    },
    {
        resourceType: "ValueSet",
        id: "expanded-value-set",
        name: "ExpandedValueSet",
        url: "http://example.test/ValueSet/expanded",
        expansion: {
            timestamp: "2026-08-19T00:00:00Z",
            contains: [{ code: "expansion-only", display: "Expansion only" }],
        },
    },
    {
        resourceType: "NamingSystem",
        id: "local-identifiers",
        name: "LocalIdentifiers",
        uniqueId: [{ type: "uri", value: "http://example.test/NamingSystem/local-identifiers", preferred: true }],
    },
] as const;

const generateTerminology = async (
    verification = "registry-integrity",
    sourceResources: readonly object[] = resources,
) => {
    const manager = {
        packageJson: async () => ({ ...packageMeta, dependencies: {} }),
        search: async () => sourceResources,
    } as unknown as Parameters<typeof registerFromManager>[0];
    const register = await registerFromManager(manager, { focusedPackages: [packageMeta] });

    const result = await new APIBuilder({ register, logger: mkErrorLogger() })
        .typescript({
            inMemoryOnly: true,
            terminology: {
                enabled: true,
                packageVerification: { "fixture.ig@1.2.3": verification },
            },
        })
        .generate();

    if (!result.success) throw new Error(`generation failed: ${result.errors.join(", ")}`);
    const output = result.filesGenerated.typescript!["generated/types/fixture-ig/terminology.ts"];
    if (output === undefined) throw new Error("terminology module was not generated");
    return output;
};

describe("TypeScript terminology surface", () => {
    it("does not emit terminology unless explicitly enabled", async () => {
        const manager = {
            packageJson: async () => ({ ...packageMeta, dependencies: {} }),
            search: async () => resources,
        } as unknown as Parameters<typeof registerFromManager>[0];
        const register = await registerFromManager(manager, { focusedPackages: [packageMeta] });

        const result = await new APIBuilder({ register, logger: mkErrorLogger() })
            .typescript({ inMemoryOnly: true })
            .generate();

        expect(result.filesGenerated.typescript?.["generated/types/fixture-ig/terminology.ts"]).toBeUndefined();
    });

    it("emits package provenance and declared content for every terminology resource", async () => {
        expect(await generateTerminology()).toMatchInlineSnapshot(`
          "// WARNING: This file is autogenerated by @atomic-ehr/codegen.
          // GitHub: https://github.com/atomic-ehr/codegen
          // Any manual changes made to this file may be overwritten.

          export const CompleteExampleCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/complete",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "complete",
              codes: ["second", "first"],
              displays: {
                  ["second"]: "Second display",
                  ["first"]: "First display",
              },
          } as const;
          export type CompleteExampleCode = (typeof CompleteExampleCodeSystem.codes)[number];

          export const ExampleContentCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/example",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "example",
          } as const;

          export const NotPresentExampleCodeSystem = {
              canonicalUrl: "http://example.test/CodeSystem/not-present",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "CodeSystem",
              contentMode: "not-present",
          } as const;

          export const LocalIdentifiersNamingSystem = {
              canonicalUrl: "http://example.test/NamingSystem/local-identifiers",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "NamingSystem",
              contentMode: null,
          } as const;

          export const ExpandedValueSetValueSet = {
              canonicalUrl: "http://example.test/ValueSet/expanded",
              packageId: "fixture.ig",
              packageVersion: "1.2.3",
              verification: "registry-integrity",
              resourceType: "ValueSet",
              contentMode: null,
          } as const;
          "
        `);
    });

    it("does not derive constants from non-complete CodeSystems or ValueSet expansions", async () => {
        const output = await generateTerminology();

        expect(output).not.toContain("must-not-appear");
        expect(output).not.toContain("also-forbidden");
        expect(output).not.toContain("expansion-only");
        expect(output).not.toContain("export type NotPresentExampleCode =");
        expect(output).not.toContain("export type ExampleContentCode =");
    });

    it("projects only fields required by terminology generation into the register", async () => {
        const manager = {
            packageJson: async () => ({ ...packageMeta, dependencies: {} }),
            search: async () => [
                {
                    resourceType: "CodeSystem",
                    id: "projected",
                    name: "Projected",
                    url: "http://example.test/CodeSystem/projected",
                    content: "complete",
                    concept: [
                        {
                            code: "kept",
                            display: "Kept display",
                            designation: [{ language: "de", value: "Discarded designation" }],
                            property: [{ code: "status", valueCode: "active" }],
                        },
                    ],
                    meta: { profile: ["http://example.test/Profile/discarded"] },
                },
                {
                    resourceType: "ValueSet",
                    id: "projected-value-set",
                    name: "ProjectedValueSet",
                    url: "http://example.test/ValueSet/projected",
                    compose: { include: [{ system: "http://example.test/CodeSystem/projected" }] },
                    expansion: { contains: [{ code: "discarded-expansion" }] },
                },
            ],
        } as unknown as Parameters<typeof registerFromManager>[0];

        const register = await registerFromManager(manager, { focusedPackages: [packageMeta] });

        expect(register.allTerminology()).toEqual([
            {
                packageMeta,
                resources: [
                    {
                        resourceType: "CodeSystem",
                        id: "projected",
                        name: "Projected",
                        url: "http://example.test/CodeSystem/projected",
                        content: "complete",
                        concept: [{ code: "kept", display: "Kept display" }],
                    },
                    {
                        resourceType: "ValueSet",
                        id: "projected-value-set",
                        name: "ProjectedValueSet",
                        url: "http://example.test/ValueSet/projected",
                    },
                ],
            },
        ]);
    });

    it("preserves complete CodeSystem concept order and exact displays", async () => {
        const output = await generateTerminology();
        const sourceConcepts = resources[0].concept;

        expect(output.indexOf(JSON.stringify(sourceConcepts[0].code))).toBeLessThan(
            output.indexOf(JSON.stringify(sourceConcepts[1].code)),
        );
        for (const concept of sourceConcepts) {
            expect(output).toContain(`[${JSON.stringify(concept.code)}]: ${JSON.stringify(concept.display)}`);
        }
    });

    it("preserves __proto__ as an own display-map property at runtime", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "proto-display",
                name: "ProtoDisplay",
                url: "http://example.test/CodeSystem/proto-display",
                content: "complete",
                concept: [{ code: "__proto__", display: "Prototype display" }],
            },
        ]);
        const javascript = new Bun.Transpiler({ loader: "ts" }).transformSync(output);
        const generated = await import(`data:text/javascript;base64,${Buffer.from(javascript).toString("base64")}`);
        const displays = generated.ProtoDisplayCodeSystem.displays;

        expect(Object.hasOwn(displays, "__proto__")).toBeTrue();
        expect(Reflect.get(displays, "__proto__")).toBe("Prototype display");
    });

    it("flattens hierarchical concepts in source order with exact displays", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "hierarchical",
                name: "Hierarchical",
                url: "http://example.test/CodeSystem/hierarchical",
                content: "complete",
                concept: [
                    {
                        code: "parent",
                        display: "Parent display",
                        concept: [{ code: "child", display: "Child display" }],
                    },
                    { code: "sibling", display: "Sibling display" },
                ],
            },
        ]);

        expect(output).toContain('codes: ["parent", "child", "sibling"]');
        expect(output.indexOf('["parent"]: "Parent display"')).toBeLessThan(
            output.indexOf('["child"]: "Child display"'),
        );
        expect(output.indexOf('["child"]: "Child display"')).toBeLessThan(
            output.indexOf('["sibling"]: "Sibling display"'),
        );
    });

    it("handles deeply nested concepts without exhausting the stack", async () => {
        const depth = 12_000;
        let concept: { code: string; display: string; concept?: object[] } = {
            code: `code-${depth}`,
            display: `Display ${depth}`,
        };
        for (let index = depth - 1; index >= 0; index -= 1) {
            concept = {
                code: `code-${index}`,
                display: `Display ${index}`,
                concept: [concept],
            };
        }

        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "deep-hierarchy",
                name: "DeepHierarchy",
                url: "http://example.test/CodeSystem/deep-hierarchy",
                content: "complete",
                concept: [concept],
            },
        ]);

        expect(output).toContain('codes: ["code-0", "code-1"');
        expect(output).toContain(`["code-${depth}"]: "Display ${depth}"`);
    });

    it("fails deterministically when hierarchical concepts repeat a code", async () => {
        const generation = generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "duplicate-code",
                name: "DuplicateCode",
                url: "http://example.test/CodeSystem/duplicate-code",
                content: "complete",
                concept: [
                    { code: "same", display: "Parent display", concept: [{ code: "same", display: "Child display" }] },
                ],
            },
        ]);

        await expect(generation).rejects.toThrow(
            'CodeSystem http://example.test/CodeSystem/duplicate-code repeats code "same"',
        );
    });

    it("fails deterministically when one package repeats a resource type and canonical URL", async () => {
        const generation = generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "first-duplicate",
                name: "FirstDuplicate",
                url: "http://example.test/CodeSystem/duplicate-canonical",
                content: "complete",
                concept: [{ code: "first", display: "First display" }],
            },
            {
                resourceType: "CodeSystem",
                id: "second-duplicate",
                name: "SecondDuplicate",
                url: "http://example.test/CodeSystem/duplicate-canonical",
                content: "complete",
                concept: [{ code: "second", display: "Second display" }],
            },
        ]);

        await expect(generation).rejects.toThrow(
            'Package fixture.ig@1.2.3 contains duplicate CodeSystem canonical URL "http://example.test/CodeSystem/duplicate-canonical" for resources first-duplicate, second-duplicate',
        );
    });

    it("emits no concept content for an unverifiable package", async () => {
        const output = await generateTerminology("unverifiable");

        expect(output).toContain('canonicalUrl: "http://example.test/CodeSystem/complete"');
        expect(output).toContain('packageVersion: "1.2.3"');
        expect(output).toContain('verification: "unverifiable"');
        expect(output).not.toContain("codes:");
        expect(output).not.toContain("displays:");
        expect(output).not.toContain("export type CompleteExampleCode");
    });

    it("derives NamingSystem identity from URI, OID-only, and other-only unique identifiers", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "NamingSystem",
                id: "uri-identity",
                name: "UriIdentity",
                uniqueId: [{ type: "uri", value: "http://example.test/NamingSystem/uri", preferred: true }],
            },
            {
                resourceType: "NamingSystem",
                id: "oid-identity",
                name: "OidIdentity",
                uniqueId: [{ type: "oid", value: "1.2.276.0.76.3.1", preferred: true }],
            },
            {
                resourceType: "NamingSystem",
                id: "other-identity",
                name: "OtherIdentity",
                uniqueId: [{ type: "other", value: "practice-local-identifier", preferred: true }],
            },
        ]);

        expect(output).toContain('canonicalUrl: "http://example.test/NamingSystem/uri"');
        expect(output).toContain('canonicalUrl: "urn:oid:1.2.276.0.76.3.1"');
        expect(output).toContain('canonicalUrl: "practice-local-identifier"');
        expect([...output.matchAll(/^export const /gm)]).toHaveLength(3);
    });

    it("disambiguates resources that declare the same FHIR name", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "ValueSet",
                id: "radiation-relevant-billing-code",
                name: "RadiationRelevantBillingCodeVS",
                url: "http://example.test/ValueSet/radiation-relevant-billing-code",
            },
            {
                resourceType: "ValueSet",
                id: "radiation-relevant-billing-codes",
                name: "RadiationRelevantBillingCodeVS",
                url: "http://example.test/ValueSet/radiation-relevant-billing-codes",
            },
        ]);

        const symbols = [...output.matchAll(/^export const (\w+)/gm)].map((match) => match[1]);
        expect(symbols).toHaveLength(2);
        expect(new Set(symbols).size).toBe(2);
        expect(() => new Bun.Transpiler({ loader: "ts" }).transformSync(output)).not.toThrow();
    });

    it("emits byte-identical terminology and stable symbols when discovery order reverses", async () => {
        const discovered = [
            {
                resourceType: "ValueSet",
                id: "zeta",
                name: "SharedName",
                url: "http://example.test/ValueSet/zeta",
            },
            {
                resourceType: "ValueSet",
                id: "alpha",
                name: "SharedName",
                url: "http://example.test/ValueSet/alpha",
            },
            {
                resourceType: "ValueSet",
                id: "unique",
                name: "UniqueName",
                url: "http://example.test/ValueSet/unique",
            },
        ];

        const forward = await generateTerminology("registry-integrity", discovered);
        const reversed = await generateTerminology("registry-integrity", discovered.toReversed());

        expect(reversed).toBe(forward);
        expect(forward).toContain("export const UniqueNameValueSet =");
        expect(forward).toContain("export const SharedNameValueSet_Alpha =");
        expect(forward).toContain("export const SharedNameValueSet_Zeta =");
        expect(forward.indexOf('canonicalUrl: "http://example.test/ValueSet/alpha"')).toBeLessThan(
            forward.indexOf('canonicalUrl: "http://example.test/ValueSet/zeta"'),
        );
    });

    it("emits valid identifiers and adjacent code-union names for punctuation and leading digits", async () => {
        const output = await generateTerminology("registry-integrity", [
            {
                resourceType: "CodeSystem",
                id: "3-weird-terms",
                name: "3/Weird (Doctor's), Terms",
                url: "http://example.test/CodeSystem/3-weird-terms",
                content: "complete",
                concept: [{ code: "valid", display: "Valid display" }],
            },
        ]);

        expect(output).toContain("export const _3_Weird_Doctor_s_TermsCodeSystem =");
        expect(output).toContain("export type _3_Weird_Doctor_s_TermsCode =");
        expect(() => new Bun.Transpiler({ loader: "ts" }).transformSync(output)).not.toThrow();
    });

    it("emits both versions when a prebuilt public register contains the same package twice", async () => {
        const packageVersions = [
            { name: "fixture.ig", version: "1.0.0" },
            { name: "fixture.ig", version: "2.0.0" },
        ];
        const manager = {
            packageJson: async () => ({ dependencies: {} }),
            search: async ({ package: pkg }: { package: { version: string } }) => [
                {
                    resourceType: "ValueSet",
                    id: `version-${pkg.version}`,
                    name: `Version${pkg.version}`,
                    url: `http://example.test/ValueSet/${pkg.version}`,
                },
            ],
        } as unknown as Parameters<typeof registerFromManager>[0];
        const register = await registerFromManager(manager, { focusedPackages: packageVersions });

        const result = await new APIBuilder({ register, logger: mkErrorLogger() })
            .typescript({
                inMemoryOnly: true,
                terminology: {
                    enabled: true,
                    packageVerification: {
                        "fixture.ig@1.0.0": "registry-integrity",
                        "fixture.ig@2.0.0": "registry-integrity",
                    },
                },
            })
            .generate();

        const first = result.filesGenerated.typescript?.["generated/types/fixture-ig-1-0-0/terminology.ts"];
        const second = result.filesGenerated.typescript?.["generated/types/fixture-ig-2-0-0/terminology.ts"];
        expect(first).toContain('packageVersion: "1.0.0"');
        expect(second).toContain('packageVersion: "2.0.0"');
        expect(first).toContain('canonicalUrl: "http://example.test/ValueSet/1.0.0"');
        expect(second).toContain('canonicalUrl: "http://example.test/ValueSet/2.0.0"');
    });

    it("preserves packages whose normalized directories collide and contains unsafe path characters", async () => {
        const packageMetas = [
            { name: "fixture.ig", version: "1.0.0" },
            { name: "fixture-ig", version: "1.0.0" },
            { name: "..\\outside/fixture.ig", version: "1.0.0" },
        ];
        const manager = {
            packageJson: async () => ({ dependencies: {} }),
            search: async ({ package: pkg }: { package: { name: string } }) => [
                {
                    resourceType: "ValueSet",
                    id: "package-identity",
                    name: "PackageIdentity",
                    url: `http://example.test/ValueSet/${encodeURIComponent(pkg.name)}`,
                },
            ],
        } as unknown as Parameters<typeof registerFromManager>[0];
        const register = await registerFromManager(manager, { focusedPackages: packageMetas });
        const packageVerification = Object.fromEntries(
            packageMetas.map(({ name, version }) => [`${name}@${version}`, "registry-integrity"]),
        );

        const result = await new APIBuilder({ register, logger: mkErrorLogger() })
            .typescript({ inMemoryOnly: true, terminology: { enabled: true, packageVerification } })
            .generate();
        const terminologyFiles = Object.entries(result.filesGenerated.typescript ?? {}).filter(([path]) =>
            path.endsWith("/terminology.ts"),
        );

        expect(terminologyFiles).toHaveLength(3);
        expect(
            terminologyFiles
                .map(([, content]) => content.match(/packageId: ("(?:\\.|[^"])+")/)?.[1])
                .map((packageId) => (packageId === undefined ? undefined : JSON.parse(packageId)))
                .sort(),
        ).toEqual(packageMetas.map(({ name }) => name).sort());
        for (const [path] of terminologyFiles) {
            expect(path).toMatch(/^generated\/types\/[a-z0-9][a-z0-9-]*\/terminology\.ts$/);
            expect(path).not.toContain("..");
            expect(path).not.toContain("\\");
        }
    });

    it("uses one physical package directory mapping for schemas, terminology, and cross-package imports", async () => {
        const packageMetas = [
            { name: "fixture.ig", version: "1.0.0" },
            { name: "fixture-ig", version: "1.0.0" },
            { name: "versioned.ig", version: "1.0.0" },
            { name: "versioned.ig", version: "2.0.0" },
        ];
        const manager = {
            packageJson: async () => ({ dependencies: {} }),
            search: async ({ package: pkg }: { package: { name: string; version: string } }) => [
                {
                    resourceType: "ValueSet",
                    id: `terminology-${pkg.version}`,
                    name: `Terminology${pkg.version}`,
                    url: `http://example.test/${encodeURIComponent(pkg.name)}/${pkg.version}/ValueSet/terminology`,
                },
            ],
        } as unknown as Parameters<typeof registerFromManager>[0];
        const register = await registerFromManager(manager, { focusedPackages: packageMetas });
        const appendSchema = (
            pkg: { name: string; version: string },
            name: string,
            url: string,
            elements: Record<string, object>,
        ) => {
            register.testAppendFs(
                enrichFHIRSchema(
                    {
                        name,
                        type: name,
                        kind: "complex-type",
                        url,
                        elements,
                        class: "complex-type",
                    } as unknown as FHIRSchema,
                    pkg,
                ),
            );
        };
        appendSchema(packageMetas[0]!, "Shared", "http://example.test/fixture.ig/Shared", {});
        appendSchema(packageMetas[1]!, "Consumer", "http://example.test/fixture-ig/Consumer", {
            shared: { type: "http://example.test/fixture.ig/Shared" },
        });
        appendSchema(packageMetas[2]!, "Versioned", "http://example.test/versioned.ig/1/Versioned", {});
        appendSchema(packageMetas[3]!, "Versioned", "http://example.test/versioned.ig/2/Versioned", {});
        const packageVerification = Object.fromEntries(
            packageMetas.map(({ name, version }) => [`${name}@${version}`, "registry-integrity"]),
        );

        const result = await new APIBuilder({ register, logger: mkErrorLogger() })
            .typescript({ inMemoryOnly: true, terminology: { enabled: true, packageVerification } })
            .generate();
        if (!result.success) throw new Error(result.errors.join(", "));
        const files = result.filesGenerated.typescript ?? {};
        const terminologyDirectories = Object.keys(files)
            .filter((path) => path.endsWith("/terminology.ts"))
            .map((path) => path.slice(0, -"/terminology.ts".length));

        const versionedDirectories = terminologyDirectories.filter((directory) =>
            files[`${directory}/terminology.ts`]?.includes('packageId: "versioned.ig"'),
        );
        expect(versionedDirectories).toHaveLength(2);
        expect(
            versionedDirectories.map((directory) =>
                files[`${directory}/Versioned.ts`]?.includes("http://example.test/versioned.ig/1/Versioned"),
            ),
        ).toEqual([true, false]);
        expect(
            versionedDirectories.map((directory) =>
                files[`${directory}/Versioned.ts`]?.includes("http://example.test/versioned.ig/2/Versioned"),
            ),
        ).toEqual([false, true]);

        const consumerEntry = Object.entries(files).find(([path]) => path.endsWith("/Consumer.ts"));
        expect(consumerEntry).toBeDefined();
        const sharedImport = consumerEntry?.[1].match(/from "(\.\.\/[^"]+\/Shared)"/)?.[1];
        expect(sharedImport).toBeDefined();
        const consumerDirectory = consumerEntry?.[0].slice(0, -"/Consumer.ts".length);
        const importedSharedPath = join(consumerDirectory ?? "", `${sharedImport}.ts`);
        expect(files[importedSharedPath]).toBeDefined();

        const compileRoot = await mkdtemp(join(tmpdir(), "codegen-x68-package-dirs-"));
        try {
            for (const [path, content] of Object.entries(files)) {
                const target = join(compileRoot, path);
                await mkdir(dirname(target), { recursive: true });
                await Bun.write(target, content);
            }
            const compile = Bun.spawn(
                [
                    "bunx",
                    "tsc",
                    "--noEmit",
                    "--target",
                    "ESNext",
                    "--module",
                    "ESNext",
                    "--moduleResolution",
                    "Bundler",
                    "--skipLibCheck",
                    ...Object.keys(files)
                        .filter((path) => path.endsWith(".ts"))
                        .map((path) => join(compileRoot, path)),
                ],
                { stdout: "pipe", stderr: "pipe" },
            );
            const compileOutput = `${await new Response(compile.stdout).text()}${await new Response(compile.stderr).text()}`;
            expect({ exitCode: await compile.exited, output: compileOutput }).toEqual({ exitCode: 0, output: "" });
        } finally {
            await rm(compileRoot, { recursive: true, force: true });
        }
    });
});
