// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeSystem } from "./hl7-fhir-r4-core/CodeSystem";

export type TerminologyVerification = "registry-integrity" | "unverifiable" | (string & {});

type TerminologyEntryBase = {
    canonicalUrl: string;
    packageId: string;
    packageVersion: string;
    verification: TerminologyVerification;
};

/** `contentMode` is a CodeSystem concept; the other entry kinds have none. */
export type CodeSystemEntry = TerminologyEntryBase & {
    resourceType: "CodeSystem";
    contentMode?: CodeSystem["content"];
};

export type ValueSetEntry = TerminologyEntryBase & {
    resourceType: "ValueSet";
};

export type NamingSystemEntry = TerminologyEntryBase & {
    resourceType: "NamingSystem";
};

/** One normalized terminology resource, discriminated by `resourceType`. */
export type TerminologyEntry = CodeSystemEntry | ValueSetEntry | NamingSystemEntry;

/** A complete CodeSystem whose codes are embedded: the simplified runtime surface. */
export type CodedTerminologyEntry<Code extends string = string> = CodeSystemEntry & {
    contentMode: "complete";
    codes: readonly Code[];
    displays: Readonly<Partial<Record<Code, string>>>;
};
