# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import Any, Literal, cast, overload

from fhir_types.hl7_fhir_r4_core.provenance import Provenance
from fhir_types.hl7_fhir_r4_core.base import BackboneElement, Reference
from fhir_types.hl7_fhir_r4_core.provenance import ProvenanceAgent
from fhir_types.profile_helpers import (
    apply_slice_match, build_resource, ensure_profile, get_array_slice, matches_value, set_array_slice, strip_match_keys, \
    validate_reference, validate_required
)


class UscoreProvenanceProfile:
    """The US Core Provenance Profile inherits from the FHIR [Provenance](https://hl7.org/fhir/R4/provenance.html) resource; refer to it for scope and usage definitions. This profile sets minimum expectations for the Provenance resource to record, search, and fetch provenance information associated with a record. It covers the minimal (basic) information to support lineage of information. It specifies which core elements, extensions, vocabularies, and value sets **SHALL** be present and constrains how the elements are used.   Before reviewing this profile, implementers are encouraged to read the Basic Provenance guidance page, which documents several key use cases, specifically, the organization responsible for the most recent action on the resource.

    CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance
    """

    resource_type: str = "Provenance"
    canonical_url: str = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance"

    _provenance_author_slice_match: dict[str, Any] = {"type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/provenance-participant-type","code":"author"}]}}
    _provenance_transmitter_slice_match: dict[str, Any] = {"type":{"coding":[{"system":"http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type","code":"transmitter"}]}}

    def __init__(self, resource: Provenance) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Provenance) -> "UscoreProvenanceProfile":
        meta = getattr(resource, "meta", None)
        profiles = getattr(meta, "profile", None) if meta is not None else None
        if profiles is None or cls.canonical_url not in profiles:
            raise ValueError(f"UscoreProvenanceProfile: meta.profile must include {cls.canonical_url}")
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Provenance) -> "UscoreProvenanceProfile":
        ensure_profile(resource, cls.canonical_url)
        return cls(resource)

    @classmethod
    def create_resource(cls, *, target: list[Reference], recorded: str, agent: list[BackboneElement]) -> Provenance:
        return build_resource(
            Provenance,
            resourceType="Provenance",
            target=target,
            recorded=recorded,
            agent=agent,
            meta={"profile": [cls.canonical_url]},
        )

    @classmethod
    def create(cls, *, target: list[Reference], recorded: str, agent: list[BackboneElement]) -> "UscoreProvenanceProfile":
        return cls.apply(cls.create_resource(target=target, recorded=recorded, agent=agent))

    def to_resource(self) -> Provenance:
        return self._resource

    def get_target(self) -> list[Reference] | None:
        return cast('list[Reference] | None', getattr(self._resource, "target", None))

    def set_target(self, value: list[Reference]) -> "UscoreProvenanceProfile":
        setattr(self._resource, "target", value)
        return self

    def get_recorded(self) -> str | None:
        return cast('str | None', getattr(self._resource, "recorded", None))

    def set_recorded(self, value: str) -> "UscoreProvenanceProfile":
        setattr(self._resource, "recorded", value)
        return self

    def get_agent(self) -> list[BackboneElement] | None:
        return cast('list[BackboneElement] | None', getattr(self._resource, "agent", None))

    def set_agent(self, value: list[BackboneElement]) -> "UscoreProvenanceProfile":
        setattr(self._resource, "agent", value)
        return self

    @overload
    def get_provenance_author(self) -> dict[str, Any] | None: ...
    @overload
    def get_provenance_author(self, mode: Literal["raw"]) -> ProvenanceAgent | None: ...
    def get_provenance_author(self, mode: Literal["raw"] | None = None) -> dict[str, Any] | ProvenanceAgent | None:
        match = self.__class__._provenance_author_slice_match
        item = get_array_slice(getattr(self._resource, "agent", None), match)
        if mode == "raw":
            return cast('ProvenanceAgent | None', item)
        item_dict = item if isinstance(item, dict) else item.model_dump(by_alias=True, exclude_none=True)
        return strip_match_keys(item_dict, ["type"])

    @overload
    def get_provenance_transmitter(self) -> dict[str, Any] | None: ...
    @overload
    def get_provenance_transmitter(self, mode: Literal["raw"]) -> ProvenanceAgent | None: ...
    def get_provenance_transmitter(self, mode: Literal["raw"] | None = None) -> dict[str, Any] | ProvenanceAgent | None:
        match = self.__class__._provenance_transmitter_slice_match
        item = get_array_slice(getattr(self._resource, "agent", None), match)
        if mode == "raw":
            return cast('ProvenanceAgent | None', item)
        item_dict = item if isinstance(item, dict) else item.model_dump(by_alias=True, exclude_none=True)
        return strip_match_keys(item_dict, ["type"])

    def set_provenance_author(self, value: dict[str, Any] | None = None) -> "UscoreProvenanceProfile":
        match = self.__class__._provenance_author_slice_match
        merged = apply_slice_match((value or {}), match)
        element = ProvenanceAgent(**merged)
        items = getattr(self._resource, "agent", None) or []
        set_array_slice(items, match, element)
        setattr(self._resource, "agent", items)
        return self

    def set_provenance_transmitter(self, value: dict[str, Any] | None = None) -> "UscoreProvenanceProfile":
        match = self.__class__._provenance_transmitter_slice_match
        merged = apply_slice_match((value or {}), match)
        element = ProvenanceAgent(**merged)
        items = getattr(self._resource, "agent", None) or []
        set_array_slice(items, match, element)
        setattr(self._resource, "agent", items)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "UscoreProvenanceProfile"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "target"))
        errors.extend(
            validate_reference(self._resource, profile_name, "target", [
                "Bundle","Observation","OperationOutcome","Organization","Patient","Provenance"
        ]))
        errors.extend(validate_required(self._resource, profile_name, "recorded"))
        errors.extend(validate_required(self._resource, profile_name, "agent"))
        return {"errors": errors, "warnings": warnings}

