# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Any, List as PyList, Literal
from typing_extensions import Self
from fhir_types.fhirpy_base_model import FhirpyBaseModel

from fhir_types.hl7_fhir_r4_core.base import (
    BackboneElement, CodeableConcept, Period, Reference, Signature
)
from fhir_types.hl7_fhir_r4_core.domain_resource import DomainResource
from fhir_types.hl7_fhir_r4_core.base import Element


class ProvenanceAgent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    onBehalfOf: Reference[Literal["Device", "Organization", "Patient", "Practitioner", "PractitionerRole", "RelatedPerson"]] | None = Field(None, alias="onBehalfOf", serialization_alias="onBehalfOf")
    role: PyList[CodeableConcept] | None = Field(None, alias="role", serialization_alias="role")
    type: CodeableConcept[Literal["enterer", "performer", "author", "verifier", "legal", "attester", "informant", "custodian", "assembler", "composer"] | str] | None = Field(None, alias="type", serialization_alias="type")
    who: Reference[Literal["Device", "Organization", "Patient", "Practitioner", "PractitionerRole", "RelatedPerson"]] = Field(alias="who", serialization_alias="who")

class ProvenanceEntity(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    agent: PyList[ProvenanceAgent] | None = Field(None, alias="agent", serialization_alias="agent")
    role: Literal["derivation", "revision", "quotation", "source", "removal"] = Field(alias="role", serialization_alias="role")
    what: Reference = Field(alias="what", serialization_alias="what")


class Provenance(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    resourceType: str = Field(
        default='Provenance',
        alias='resourceType',
        serialization_alias='resourceType',
        pattern='Provenance'
    )
    activity: CodeableConcept[Literal["LA", "ANONY", "DEID", "MASK", "LABEL", "PSEUD", "CREATE", "DELETE", "UPDATE", "APPEND", "NULLIFY", "PART", "_ParticipationAncillary", "ADM", "ATND", "CALLBCK", "CON", "DIS", "ESC", "REF", "_ParticipationInformationGenerator", "AUT", "INF", "TRANS", "ENT", "WIT", "CST", "DIR", "ALY", "BBY", "CAT", "CSM", "TPA", "DEV", "NRD", "RDV", "DON", "EXPAGNT", "EXPART", "EXPTRGT", "EXSRC", "PRD", "SBJ", "SPC", "IND", "BEN", "CAGNT", "COV", "GUAR", "HLD", "RCT", "RCV", "IRCP", "NOT", "PRCP", "REFB", "REFT", "TRC", "LOC", "DST", "ELOC", "ORG", "RML", "VIA", "PRF", "DIST", "PPRF", "SPRF", "RESP", "VRF", "AUTHEN", "LA"] | str] | None = Field(None, alias="activity", serialization_alias="activity")
    agent: PyList[ProvenanceAgent] = Field(alias="agent", serialization_alias="agent")
    entity: PyList[ProvenanceEntity] | None = Field(None, alias="entity", serialization_alias="entity")
    location: Reference[Literal["Location"]] | None = Field(None, alias="location", serialization_alias="location")
    occurredDateTime: str | None = Field(None, alias="occurredDateTime", serialization_alias="occurredDateTime")
    occurredDateTimeExtension: Element | None = Field(None, alias="_occurredDateTime", serialization_alias="_occurredDateTime")
    occurredPeriod: Period | None = Field(None, alias="occurredPeriod", serialization_alias="occurredPeriod")
    policy: PyList[str] | None = Field(None, alias="policy", serialization_alias="policy")
    policyExtension: PyList[Element | None] | None = Field(None, alias="_policy", serialization_alias="_policy")
    reason: PyList[CodeableConcept] | None = Field(None, alias="reason", serialization_alias="reason")
    recorded: str = Field(alias="recorded", serialization_alias="recorded")
    recordedExtension: Element | None = Field(None, alias="_recorded", serialization_alias="_recorded")
    signature: PyList[Signature] | None = Field(None, alias="signature", serialization_alias="signature")
    target: PyList[Reference] = Field(alias="target", serialization_alias="target")

    def model_post_init(self, __context: Any) -> None:
        self.__pydantic_fields_set__.add("resourceType")

    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)

    @classmethod
    def from_json(cls, json: str) -> Self:
        return cls.model_validate_json(json)

